apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/orhanIBM/app1.git
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-08-13T13:14:47Z"
  labels:
    app: app-1-git
    app.kubernetes.io/component: app-1-git
    app.kubernetes.io/instance: app-1-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: app-1-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: app-1-git
  namespace: dev-oy2
  resourceVersion: "21043286"
  selfLink: /api/v1/namespaces/dev-oy2/services/app-1-git
  uid: af1054fb-cde5-44a2-9943-f844915d1664
spec:
  clusterIP: 172.21.86.114
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: app-1-git
    deploymentconfig: app-1-git
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
